export const entriesTotal = [
  'Daniele Tolomelli',
  'Veronica Ferrari',
  'Rosa Carleo',
  'Danilo Vaccalluzzo',
  'Riccardo Grandi',
  'Gabriele Gimelli',
  'Umberto Sgueglia',
  'Alessio Netti',
  'Andrea Melis',
  'Gianluca Giacchetta',
  'marco antezza',
  'Marco Giampieri',
  'Deborah Bernazzali',
  'Cesare Gamberi',
  'Vittorio Capitani',
  'Domenico Pontoriero',
  'Diego Ruotolo',
  'Mattia Reggiani',
  'Cristiano Souza Paz Fiorio',
  'Giulia Cantini',
  'Barbaro Pappalardo',
  'Mauro Medad',
  'francesca De pasquale',
  'Riccardo Maffei',
  'Emanuele Bencivenni',
  'Silvia Severini',
  'Davide Petti',
  'Darius Pasca',
  'Prasanna Kavisha Wickramasinghe',
  'Matteo Berti',
  'Matteo Semeraro',
  'Alessandro Francesconi',
  'Federico Bertani',
  'Matteo Del Vecchio',
  'Valentina Tosto',
  'Arianna Goldoni',
  'Salvatore Fiorilla',
  'Gianmarco Spinaci',
  'Andrea Cuccovillo',
  'Giuseppe Travasoni',
  'Fabio Viggiano',
  'ferdinando granelli',
  'Stefano Girotti',
  'Simone Bonfante',
  'Riccardo Scaramagli',
  'erica tizzoni',
  'lorenzo cazzoli',
  'George Daniel Lungu',
  'Marco Valerio Manzini',
  'Cristian Castiglione',
  'Simone Severi',
  'Michele D\'onza',
  'Pamela Rossi',
  'Davide Montanari',
  'EVA BALLARANI',
  'Mattia Franzoni',
  'Nicola Gentilini',
  'Samuele Resca',
  'Federico Govoni',
  'Roberto Luise',
  'diego maranini',
  'Enrico Martelli',
].map(entry => entry.toLowerCase()).sort();

export const entriesShirts = [
  'Mattia Reggiani',
  'Cristiano Souza Paz Fiorio',
  'Giulia Cantini',
  'Barbaro Pappalardo',
  'Mauro Medad',
  'francesca De pasquale',
  'Riccardo Maffei',
  'Emanuele Bencivenni',
  'Silvia Severini',
  'Davide Petti',
  'Darius Pasca',
  'Prasanna Kavisha Wickramasinghe',
  'Matteo Berti',
  'Matteo Semeraro',
  'Alessandro Francesconi',
  'Federico Bertani',
  'Matteo Del Vecchio',
  'Valentina Tosto',
  'Arianna Goldoni',
  'Salvatore Fiorilla',
  'Gianmarco Spinaci',
  'Andrea Cuccovillo',
  'Giuseppe Travasoni',
  'Fabio Viggiano',
  'ferdinando granelli',
  'Stefano Girotti',
  'Simone Bonfante',
  'Riccardo Scaramagli',
  'erica tizzoni',
  'lorenzo cazzoli',
  'George Daniel Lungu',
  'Marco Valerio Manzini',
  'Cristian Castiglione',
  'Simone Severi',
  'Michele D\'onza',
  'Pamela Rossi',
  'Davide Montanari',
  'EVA BALLARANI',
  'Mattia Franzoni',
  'Nicola Gentilini',
  'Samuele Resca',
  'Federico Govoni',
  'Roberto Luise',
  'diego maranini',
  'Enrico Martelli',
].map(entry => entry.toLowerCase()).sort();
