export const entriesTotal = [
  'Daniele Tolomelli',
  'Veronica Ferrari',
  'Rosa Carleo',
  'Gabriele Gimelli',
  'Umberto Sgueglia',
  'Alessio Netti',
  'Gianluca Giacchetta',
  'Marco Giampieri',
  'Deborah Bernazzali',
  'Cesare Gamberi',
  'Vittorio Capitani',
  'Diego Ruotolo',
  'Mattia Reggiani',
  'Cristiano Souza Paz Fiorio',
  'Barbaro Pappalardo',
  'francesca De pasquale',
  'Riccardo Maffei',
  'Emanuele Bencivenni',
  'Davide Petti',
  'Darius Pasca',
  'Prasanna Kavisha Wickramasinghe',
  'Matteo Berti',
  'Matteo Semeraro',
  'Alessandro Francesconi',
  'Federico Bertani',
  'Matteo Del Vecchio',
  'Giuseppe Travasoni',
  'Stefano Girotti',
  'Riccardo Scaramagli',
  'erica tizzoni',
  'lorenzo cazzoli',
  'Simone Severi',
  'Michele D\'onza',
  'Pamela Rossi',
  'EVA BALLARANI',
  'Nicola Gentilini',
  'Federico Govoni',
  'Roberto Luise',
  'diego maranini',
  'Enrico Martelli',
  'Alessandro Cocilova',
  'Gianmarco Canello',
  'Giacomo Rizzi',
  'Matteo Barato',
  'Marco Armone',
  'Denise Alessi',
].map(entry => entry.toLowerCase()).sort();

export const entriesShirts = [
  'Mattia Reggiani',
  'Cristiano Souza Paz Fiorio',
  'Barbaro Pappalardo',
  'francesca De pasquale',
  'Riccardo Maffei',
  'Emanuele Bencivenni',
  'Davide Petti',
  'Darius Pasca',
  'Prasanna Kavisha Wickramasinghe',
  'Matteo Berti',
  'Matteo Semeraro',
  'Alessandro Francesconi',
  'Federico Bertani',
  'Matteo Del Vecchio',
  'Giuseppe Travasoni',
  'Stefano Girotti',
  'Riccardo Scaramagli',
  'erica tizzoni',
  'lorenzo cazzoli',
  'Simone Severi',
  'Michele D\'onza',
  'Pamela Rossi',
  'EVA BALLARANI',
  'Nicola Gentilini',
  'Federico Govoni',
  'Roberto Luise',
  'diego maranini',
  'Enrico Martelli',
].map(entry => entry.toLowerCase()).sort();
